= Scrum
:sectnums:
:toc: left
:toclevels: 5
:icons: font
:source-highlighter: coderay

== Как появился Agile

=== Подходы к управлению

*классические*

Водопад (waterfall).
На этапе планирования все предусмотреть невозможно, могут появиться новые требования.

*гибкие*

Agile.
Короткие спринты и изменения имеющие ценность для бизнеса.
Был основан в 2001 году в штате Юта.

=== Agile manifest:

1. Ценности:

* Люди и взаимодействие важнее процессов и инструментов
* Сотрудничество с заказчиком важнее согласования условий контракта
* Рабочий продукт важнее исчерпывающей документации
* Готовность к изменениям важнее следования первоначальному плану

2. Принципы Agile-разработки:

* 12 штук (не перечислены в уроке)

3. В основе:

* Гибкость
* Простая структура
* Кросс функциональность
* Нацеленность на результат

== Столпы Scrum

Эмпирические столпы

* Прозрачность
* Инспекция
* Адаптация

Скрам основан на эмпиризме - единственным источником знаний является опыт, а принятие решений основывается на наблюдении.

Все столпы держался на фундаменте - доверие в организации и команде.

=== Инспекция

Для выявления нежелательных проблем необходимо регулярно и тщательно инспектировать прогресс в достижении целей.

Для инспекции существуют пять событий:

* Sprint
* Sprint planning
* Daily scrum
* Sprint review

Инспекция направлена на улучшение.

Инспекция делает возможной адаптацию.
Инспекция без адаптации считается бессмысленной.

=== Адаптация

Если в ходе инспекции команда понимает, что есть отклонения от процесса или несоответствие продукта ожиданиям конечного пользователя, необходимо выработать план по улучшению.
Чтобы минимизировать отклонения, корректировка должна быть быстрой.

Скрам тим адаптируется в тот момент, когда узнает что-то новое при инспекции.

=== Прозрачность

Прозрачность должна быть видна и тем, кто выполняет работу и тем, кто получает ценность.

* Общая терминология для всех участников процесса
* Общее понимание критериев готовности

Прозрачность делает возможной инспекцию.
Инспекция без прозрачности вводит в заблуждение.

== Ценности скрам

* приверженность
* сфокусированность
* открытость
* уважение
* смелость

== Что такое спринт

Это временной цикл работы скрам тим.

Скрам тим берет на себя обязательство достичь спринт goal.

Sprint goal - обеспечивает связанность и сфокусированность.
Побуждая скрам тим работать совместно.
Описывает потенциально готовое к использованию приращение ценности, которые клиенты могут применить.

Примеры ценностей:

* Внедрение новой функциональности на сайт
* Прототип мобильного приложения

Длительность спринта не должна превышать один месяц.

Чем меньше цикл, тем меньше рисков получить результат не тот, который нужен заинтересованным лицам.

Спринт продолжается как правило 2 недели.
Начинается и завершается в определенные даты.
Продление не допускается.
Завершить спринт досрочно может только product owner, если Sprint Goal перестала быть актуальной.

Задача команды за спринт достигнуть Sprint Goal, и для этого в Sprint Planning создается Sprint Backlog, в него вносятся задачи, требуемые для достижения спринт Goal.

Команда не берет во время спринта никаких дополнительных задач, которые могут поставить под угрозу выполнение Sprint Goal.

Спринт начитается со Sprint Planning и завершается Sprint review and Sprint Retrospective.

Ежедневная инспекция и адаптация проводится на Daily Scrum.

== Артефакты Scrum

Представляют собой работу, которую необходимо выполнить.
И делают информацию о проекте прозрачной и понятной для всех участников.

Артефакты:

* product backlog
* sprint backlog
* increment

=== Product backlog

Упорядоченный и постоянно обновляемый список элементов, необходимый для развития продукта.

Ответственность за Product backlog несет Product Owner.
Размер элементов оценивают developers.

В Product backlog входит Product goal

Product goal - описывает будущее состояние продукта, это долгосрочный ожидаемый результат Scrum Team.

В ходе планирования спринта Scrum Team принимает решение, какие элементы из Sprint backlog могут быть реализованы до готовности в течение одного спринта.

=== Sprint backlog

Наглядный и доступный в режиме реального времени план работы, который обновляется на протяжении всего спринта.
По мере появления новой информации, уточнений и деталей.
Он служит для нагладного представления работы, которую команда определила для достижения Sprint Goal.
И визуализируется на доске спринта.

*Состоит из:*

* Sprint Goal - отвечающей на вопрос "Зачем делать"
* Набора элементов в Product Backlog, выбранных в текущем спринте, отвечающих на вопрос "Что делать"
* Осуществимого плана действий по поставке increment, то есть конкретной ступени к достижению product backlog в рамках выбранных элементов.
Этот план отвечает на вопрос "Как делать"

=== Increment

Это конкретная ступень в достижении Product Goal.
Каждый increment тщательно проверяется и является дополнением ко всем предыдущим для обеспечения из успешной совместной работы.

В рамках одного спринта можно создать несколько increments.

Итоговые increments предоставляются в рамках мероприятия - обзор спринта.
Однако, заинтересованным лицам они могут поставляться еще до окончания спринта.

Работа не может быть частью increment, если она не соответствует определению готовности.

*Определение готовности* - это описание состояния increment, при котором он соответствует требованиям качествам, предъявляемым продукту.

Если элемент Product Backlog не соответствует определению готовности, то его нельзя выпускать или даже показывать на Sprint Review.
Вместо этого он возвращается в ProductBacklog для дальнейшего рассмотрения.

В момент, когда элемент Product Backlog стал соответствовать определению готовности - рождается Increment.

== Планирование спринта

== Ежедневный скрам

== Обзор спринта

== Ретроспектива спринта

== Скрам команда

== Продукт Процесс Проект

