= PostgreSQL sources list
:sectnums:
:toc: left
:toclevels: 5
:icons: font
:source-highlighter: coderay

== JMM (Model)

=== Approved

==== The Java Language Specification JLS 17

This is the official documentation for the Java programming language and includes a detailed explanation of the Java Memory Model.

https://docs.oracle.com/javase/specs/jls/se17/html/jls-17.html

==== Digital Ocean Articles

https://www.digitalocean.com/community/tutorials/java-jvm-memory-model-memory-management-in-java

==== Jenkov jmm

https://jenkov.com/tutorials/java-concurrency/java-memory-model.html

=== NOT Approved

==== Close Encounters of The Java Memory Model Kind

https://shipilev.net/blog/2016/close-encounters-of-jmm-kind/

==== Java Memory Model Pragmatics (transcript)

https://shipilev.net/blog/2014/jmm-pragmatics/

==== Java Concurrency in Practice by Brian Goetz

This book is widely regarded as one of the best resources for learning about Java concurrency, including the Java Memory Model.

==== Java Performance

The Definitive Guide by Scott Oaks - This book provides a deep dive into the performance aspects of the Java programming language, including the Java Memory Model.

== JMM (Management)

=== Approved

==== Garbage Collection и JVM

https://habr.com/ru/companies/otus/articles/776342/

==== Дюк, вынеси мусор!

https://habr.com/ru/articles/269621/

